#title: EGO EXPERIMENTS
description: Ego Experiments Studios Ltd.
show_downloads: false
google_analytics:
theme: jekyll-theme-slate
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme

